Use `core::error` instead of `std::error` to increase compatibility in `no_std` environments
rust-bitcoin/rust-secp256k1 pull request #597
Opened 2023-04-03 09:15 UTC by OverOrion

There is a `thiserror` fork called `thiserror-core` which allows it to be used in `no_std` environments.

I added a new feature flag `core-error` which enables the currently not yet stabilized `error_in_core` feature.
This enables the `thiserror-core` crate to work fine.

2023-04-03 14:04 UTC, apoelstra commented
So, as written this is definitely going to fail CI because the `error_in_core` feature is nightly-only.

I can understand the desire to have this, but adding a feature flag that requires a nightly compiler is a tough pill for us to swallow ... it means that we have to explicitly list all the non-nightly features rather than using `--all-features` in our CI runs, and it will mean continual CI breakage as this unstable API changes out from under us.

2023-04-03 14:51 UTC, OverOrion commented
Thank you for the quick and open feedback.

I understand your concerns regarding `nightly` only features. Is there anything we could do to help with it?

> it means that we have to explicitly list all the non-nightly features rather than using --all-features

I am more than happy to rewrite the feature gate like this:
```diff
-#![cfg_attr(feature = "core-error", feature(error_in_core))]
+#![cfg_attr(all(feature = "core-error", not(feature = "std")), feature(error_in_core))]
```
So this would only be used if explicitly enabled without the `std` feature. Is it something that would helpful?

The [`error_in_core` PR ](https://github.com/rust-lang/rust/issues/103765#user-content-fn-1-50b271348074af9d9aca74c4cb4c8ea0) seems to be pretty stable, or at least there is not much complaints on its issue page, so in theory it should not mean continual CI breakage.

2023-04-03 14:55 UTC, apoelstra commented
>So this would only be used if explicitly enabled without the std feature. Is it something that would helpful?

This is a cool idea, but unfortunately it would then break additivity of features -- meaning that if somebody included `secp256k1` with the `core-error` feature and then another dependency in the tree included it with `std`, Cargo would enable both and cause the first party's code to break.

2023-04-18 04:03 UTC, Kixunil requested changes

2023-04-18 04:03 UTC, Kixunil commented on Cargo.toml
> +core-error = []
If we're going to use this, I'd want the feature to be named `unstable-nightly-core-error` and document the limitations.

2023-04-18 04:03 UTC, Kixunil commented on src/lib.rs
> +}
Why duplicate this? You could just modify the condition above.

2023-04-18 04:10 UTC, Kixunil commented
> The [`error_in_core` PR ](https://github.com/rust-lang/rust/issues/103765#user-content-fn-1-50b271348074af9d9aca74c4cb4c8ea0) seems to be pretty stable

I don't think so. There's whole new provider API that's being discussed and I'm not sure `core::error::Error` can be stabilized without it.

@apoelstra I'm not sure it'd break additivity since if the feature is enabled presumably the trait in `std` is the same as in `core` so they should be interoperable. But someone would have to test that.

2023-04-18 07:44 UTC, OverOrion commented
Thanks for the feedback @Kixunil.

Just for clarification: are you willing to merge it if the requested changes has been made?

2023-04-18 08:45 UTC, Kixunil commented
I wouldn't be opposed to it but it's not my call. Once it stabilizes we can conditionally enable it from build script as we do for other things, which would be nicer.

2023-04-18 19:59 UTC, Kixunil commented
In principle we could detect nightly but we shouldn't because it'll break if they decide to change the API or something. Opting into instability should be explicit. (That's why I asked to rename the feature.)

2023-04-18 20:08 UTC, apoelstra commented
@Kixunil could we do both (require a feature, but disable it on non-nightly)?

2023-04-18 20:34 UTC, Kixunil commented
If someone actually depended on it they'd get error much later in compilation which is not nice. I'd prefer we just avoid using `--all-features` in that case.

2024-12-05 09:10 UTC, closed without merging